"""Add chat models

Revision ID: 3acde1ae4f6e
Revises: 870d2ef8b63a
Create Date: 2026-01-18 17:41:25.320859

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '3acde1ae4f6e'
down_revision = '870d2ef8b63a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publication', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('publication', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_publication_is_deleted'), 'publication', ['is_deleted'], unique=False)
    op.add_column('researcherinfo', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('researcherinfo', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_researcherinfo_is_deleted'), 'researcherinfo', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_researcherinfo_is_deleted'), table_name='researcherinfo')
    op.drop_column('researcherinfo', 'deleted_at')
    op.drop_column('researcherinfo', 'is_deleted')
    op.drop_index(op.f('ix_publication_is_deleted'), table_name='publication')
    op.drop_column('publication', 'deleted_at')
    op.drop_column('publication', 'is_deleted')
    # ### end Alembic commands ###
