"""description_of_your_changes

Revision ID: 870d2ef8b63a
Revises: 1a31ce608336
Create Date: 2025-12-17 21:56:30.436788

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '870d2ef8b63a'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('researcherinfo',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('qualification', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('institute', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('bio', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_researcherinfo_email'), 'researcherinfo', ['email'], unique=True)
    op.create_table('publication',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('researcher_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('publisher', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('domains', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['researcher_id'], ['researcherinfo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publication_researcher_id'), 'publication', ['researcher_id'], unique=False)
    op.create_table('researchercollaborator',
    sa.Column('researcher_id', sa.Uuid(), nullable=False),
    sa.Column('collaborator_id', sa.Uuid(), nullable=False),
    sa.Column('added_by', sa.Uuid(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['added_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['collaborator_id'], ['researcherinfo.id'], ),
    sa.ForeignKeyConstraint(['researcher_id'], ['researcherinfo.id'], ),
    sa.PrimaryKeyConstraint('researcher_id', 'collaborator_id')
    )
    op.create_table('publicationmember',
    sa.Column('publication_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'editor', 'viewer', name='publicationrole'), nullable=False),
    sa.Column('added_by', sa.Uuid(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['added_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['publication_id'], ['publication.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('publication_id', 'user_id')
    )
    op.drop_table('paper')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paper',
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('abstract', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name=op.f('paper_owner_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('paper_pkey'))
    )
    op.drop_table('publicationmember')
    op.drop_table('researchercollaborator')
    op.drop_index(op.f('ix_publication_researcher_id'), table_name='publication')
    op.drop_table('publication')
    op.drop_index(op.f('ix_researcherinfo_email'), table_name='researcherinfo')
    op.drop_table('researcherinfo')
    # ### end Alembic commands ###
