/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as ResearchersIdRouteImport } from './routes/researchers/$id'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutSearchRouteImport } from './routes/_layout/search'
import { Route as LayoutResearchersRouteImport } from './routes/_layout/researchers'
import { Route as LayoutProfileRouteImport } from './routes/_layout/profile'
import { Route as LayoutNotificationsRouteImport } from './routes/_layout/notifications'
import { Route as LayoutMessagesRouteImport } from './routes/_layout/messages'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutCreateRouteImport } from './routes/_layout/create'
import { Route as LayoutChatsRouteImport } from './routes/_layout/chats'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutProjectsIndexRouteImport } from './routes/_layout/projects/index'
import { Route as LayoutProjectsCreateRouteImport } from './routes/_layout/projects/create'
import { Route as LayoutProjectsIdRouteImport } from './routes/_layout/projects/$id'
import { Route as LayoutPapersIdRouteImport } from './routes/_layout/papers/$id'
import { Route as LayoutPapersIdPdfRouteImport } from './routes/_layout/papers/$id/pdf'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const ResearchersIdRoute = ResearchersIdRouteImport.update({
  id: '/researchers/$id',
  path: '/researchers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSearchRoute = LayoutSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutResearchersRoute = LayoutResearchersRouteImport.update({
  id: '/researchers',
  path: '/researchers',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProfileRoute = LayoutProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutNotificationsRoute = LayoutNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMessagesRoute = LayoutMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCreateRoute = LayoutCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutChatsRoute = LayoutChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProjectsIndexRoute = LayoutProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProjectsCreateRoute = LayoutProjectsCreateRouteImport.update({
  id: '/projects/create',
  path: '/projects/create',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProjectsIdRoute = LayoutProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPapersIdRoute = LayoutPapersIdRouteImport.update({
  id: '/papers/$id',
  path: '/papers/$id',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPapersIdPdfRoute = LayoutPapersIdPdfRouteImport.update({
  id: '/pdf',
  path: '/pdf',
  getParentRoute: () => LayoutPapersIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/chats': typeof LayoutChatsRoute
  '/create': typeof LayoutCreateRoute
  '/items': typeof LayoutItemsRoute
  '/messages': typeof LayoutMessagesRoute
  '/notifications': typeof LayoutNotificationsRoute
  '/profile': typeof LayoutProfileRoute
  '/researchers': typeof LayoutResearchersRoute
  '/search': typeof LayoutSearchRoute
  '/settings': typeof LayoutSettingsRoute
  '/researchers/$id': typeof ResearchersIdRoute
  '/': typeof LayoutIndexRoute
  '/papers/$id': typeof LayoutPapersIdRouteWithChildren
  '/projects/$id': typeof LayoutProjectsIdRoute
  '/projects/create': typeof LayoutProjectsCreateRoute
  '/projects': typeof LayoutProjectsIndexRoute
  '/papers/$id/pdf': typeof LayoutPapersIdPdfRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/chats': typeof LayoutChatsRoute
  '/create': typeof LayoutCreateRoute
  '/items': typeof LayoutItemsRoute
  '/messages': typeof LayoutMessagesRoute
  '/notifications': typeof LayoutNotificationsRoute
  '/profile': typeof LayoutProfileRoute
  '/researchers': typeof LayoutResearchersRoute
  '/search': typeof LayoutSearchRoute
  '/settings': typeof LayoutSettingsRoute
  '/researchers/$id': typeof ResearchersIdRoute
  '/': typeof LayoutIndexRoute
  '/papers/$id': typeof LayoutPapersIdRouteWithChildren
  '/projects/$id': typeof LayoutProjectsIdRoute
  '/projects/create': typeof LayoutProjectsCreateRoute
  '/projects': typeof LayoutProjectsIndexRoute
  '/papers/$id/pdf': typeof LayoutPapersIdPdfRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/chats': typeof LayoutChatsRoute
  '/_layout/create': typeof LayoutCreateRoute
  '/_layout/items': typeof LayoutItemsRoute
  '/_layout/messages': typeof LayoutMessagesRoute
  '/_layout/notifications': typeof LayoutNotificationsRoute
  '/_layout/profile': typeof LayoutProfileRoute
  '/_layout/researchers': typeof LayoutResearchersRoute
  '/_layout/search': typeof LayoutSearchRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/researchers/$id': typeof ResearchersIdRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/papers/$id': typeof LayoutPapersIdRouteWithChildren
  '/_layout/projects/$id': typeof LayoutProjectsIdRoute
  '/_layout/projects/create': typeof LayoutProjectsCreateRoute
  '/_layout/projects/': typeof LayoutProjectsIndexRoute
  '/_layout/papers/$id/pdf': typeof LayoutPapersIdPdfRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/chats'
    | '/create'
    | '/items'
    | '/messages'
    | '/notifications'
    | '/profile'
    | '/researchers'
    | '/search'
    | '/settings'
    | '/researchers/$id'
    | '/'
    | '/papers/$id'
    | '/projects/$id'
    | '/projects/create'
    | '/projects'
    | '/papers/$id/pdf'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/chats'
    | '/create'
    | '/items'
    | '/messages'
    | '/notifications'
    | '/profile'
    | '/researchers'
    | '/search'
    | '/settings'
    | '/researchers/$id'
    | '/'
    | '/papers/$id'
    | '/projects/$id'
    | '/projects/create'
    | '/projects'
    | '/papers/$id/pdf'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/chats'
    | '/_layout/create'
    | '/_layout/items'
    | '/_layout/messages'
    | '/_layout/notifications'
    | '/_layout/profile'
    | '/_layout/researchers'
    | '/_layout/search'
    | '/_layout/settings'
    | '/researchers/$id'
    | '/_layout/'
    | '/_layout/papers/$id'
    | '/_layout/projects/$id'
    | '/_layout/projects/create'
    | '/_layout/projects/'
    | '/_layout/papers/$id/pdf'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  ResearchersIdRoute: typeof ResearchersIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/researchers/$id': {
      id: '/researchers/$id'
      path: '/researchers/$id'
      fullPath: '/researchers/$id'
      preLoaderRoute: typeof ResearchersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/search': {
      id: '/_layout/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof LayoutSearchRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/researchers': {
      id: '/_layout/researchers'
      path: '/researchers'
      fullPath: '/researchers'
      preLoaderRoute: typeof LayoutResearchersRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/profile': {
      id: '/_layout/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof LayoutProfileRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/notifications': {
      id: '/_layout/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof LayoutNotificationsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/messages': {
      id: '/_layout/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof LayoutMessagesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/create': {
      id: '/_layout/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof LayoutCreateRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/chats': {
      id: '/_layout/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof LayoutChatsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/projects/': {
      id: '/_layout/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof LayoutProjectsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/projects/create': {
      id: '/_layout/projects/create'
      path: '/projects/create'
      fullPath: '/projects/create'
      preLoaderRoute: typeof LayoutProjectsCreateRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/projects/$id': {
      id: '/_layout/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof LayoutProjectsIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/papers/$id': {
      id: '/_layout/papers/$id'
      path: '/papers/$id'
      fullPath: '/papers/$id'
      preLoaderRoute: typeof LayoutPapersIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/papers/$id/pdf': {
      id: '/_layout/papers/$id/pdf'
      path: '/pdf'
      fullPath: '/papers/$id/pdf'
      preLoaderRoute: typeof LayoutPapersIdPdfRouteImport
      parentRoute: typeof LayoutPapersIdRoute
    }
  }
}

interface LayoutPapersIdRouteChildren {
  LayoutPapersIdPdfRoute: typeof LayoutPapersIdPdfRoute
}

const LayoutPapersIdRouteChildren: LayoutPapersIdRouteChildren = {
  LayoutPapersIdPdfRoute: LayoutPapersIdPdfRoute,
}

const LayoutPapersIdRouteWithChildren = LayoutPapersIdRoute._addFileChildren(
  LayoutPapersIdRouteChildren,
)

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutChatsRoute: typeof LayoutChatsRoute
  LayoutCreateRoute: typeof LayoutCreateRoute
  LayoutItemsRoute: typeof LayoutItemsRoute
  LayoutMessagesRoute: typeof LayoutMessagesRoute
  LayoutNotificationsRoute: typeof LayoutNotificationsRoute
  LayoutProfileRoute: typeof LayoutProfileRoute
  LayoutResearchersRoute: typeof LayoutResearchersRoute
  LayoutSearchRoute: typeof LayoutSearchRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutPapersIdRoute: typeof LayoutPapersIdRouteWithChildren
  LayoutProjectsIdRoute: typeof LayoutProjectsIdRoute
  LayoutProjectsCreateRoute: typeof LayoutProjectsCreateRoute
  LayoutProjectsIndexRoute: typeof LayoutProjectsIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutChatsRoute: LayoutChatsRoute,
  LayoutCreateRoute: LayoutCreateRoute,
  LayoutItemsRoute: LayoutItemsRoute,
  LayoutMessagesRoute: LayoutMessagesRoute,
  LayoutNotificationsRoute: LayoutNotificationsRoute,
  LayoutProfileRoute: LayoutProfileRoute,
  LayoutResearchersRoute: LayoutResearchersRoute,
  LayoutSearchRoute: LayoutSearchRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutPapersIdRoute: LayoutPapersIdRouteWithChildren,
  LayoutProjectsIdRoute: LayoutProjectsIdRoute,
  LayoutProjectsCreateRoute: LayoutProjectsCreateRoute,
  LayoutProjectsIndexRoute: LayoutProjectsIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  ResearchersIdRoute: ResearchersIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
